/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email/password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Too many login attempts */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create account using invite code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupInviteRequest"];
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token and issue new access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Token refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh token session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all sessions for current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out from all sessions */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordResetRequest"];
                };
            };
            responses: {
                /** @description Password reset request accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset using token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                };
            };
            responses: {
                /** @description Password reset complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/full-admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tenants */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tenants?: components["schemas"]["Tenant"][];
                            page?: components["schemas"]["PageInfo"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create tenant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTenantRequest"];
                };
            };
            responses: {
                /** @description Tenant created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tenant?: components["schemas"]["Tenant"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/full-admin/tenants/{tenantId}/invite-codes/company-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create company admin invite code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateInviteCodeRequest"];
                };
            };
            responses: {
                /** @description Invite code created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            inviteCode?: components["schemas"]["InviteCode"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/full-admin/security-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List security events across tenants */
        get: {
            parameters: {
                query?: {
                    tenantId?: string;
                    limit?: number;
                    offset?: number;
                    severity?: "INFO" | "WARN" | "ERROR";
                    eventType?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Security events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            events?: components["schemas"]["SecurityEvent"][];
                            page?: components["schemas"]["PageInfo"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant users */
        get: {
            parameters: {
                query?: {
                    role?: "COMPANY_ADMIN" | "EMPLOYEE";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users?: components["schemas"]["User"][];
                            page?: components["schemas"]["PageInfo"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/employee-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List employee profiles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Employee profile list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            profiles?: components["schemas"]["EmployeeProfile"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/security-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List security events for tenant */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    severity?: "INFO" | "WARN" | "ERROR";
                    eventType?: string;
                    q?: string;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant security events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            events?: components["schemas"]["SecurityEvent"][];
                            page?: components["schemas"]["PageInfo"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/invite-codes/employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create employee invite code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateInviteCodeRequest"];
                };
            };
            responses: {
                /** @description Invite code created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            inviteCode?: components["schemas"]["InviteCode"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/employees/{employeeUserId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert employee profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                    employeeUserId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeProfileInput"];
                };
            };
            responses: {
                /** @description Employee profile saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            profile?: components["schemas"]["EmployeeProfile"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/plan-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plan years for tenant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan year list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            planYears?: components["schemas"]["PlanYear"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create plan year */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePlanYearRequest"];
                };
            };
            responses: {
                /** @description Plan year created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            planYear?: components["schemas"]["PlanYear"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plans for tenant */
        get: {
            parameters: {
                query?: {
                    planYearId?: string;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plans?: components["schemas"]["Plan"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create plan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePlanRequest"];
                };
            };
            responses: {
                /** @description Plan created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plan?: components["schemas"]["Plan"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/company-admin/plans/{planId}/premiums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace plan premium tiers */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetPlanPremiumsRequest"];
                };
            };
            responses: {
                /** @description Premiums updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            premiums?: components["schemas"]["PlanPremium"][];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/employee/plan-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant plan years */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan years listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            planYears?: components["schemas"]["PlanYear"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/employee/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant plans */
        get: {
            parameters: {
                query?: {
                    planYearId?: string;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plans listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plans?: components["schemas"]["Plan"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/employee/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert employee profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeProfileInput"];
                };
            };
            responses: {
                /** @description Employee profile saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            profile?: components["schemas"]["EmployeeProfile"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/employee/dependents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List employee dependents */
        get: {
            parameters: {
                query?: {
                    employeeUserId?: string;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dependents listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            dependents?: components["schemas"]["Dependent"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add dependent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDependentRequest"];
                };
            };
            responses: {
                /** @description Dependent created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            dependent?: components["schemas"]["Dependent"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/employee/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List employee enrollments */
        get: {
            parameters: {
                query?: {
                    employeeUserId?: string;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enrollments listed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            enrollments?: components["schemas"]["Enrollment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/employee/enrollments/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create enrollment draft */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEnrollmentDraftRequest"];
                };
            };
            responses: {
                /** @description Draft created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            enrollment?: components["schemas"]["Enrollment"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/employee/enrollments/{enrollmentId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit enrollment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                    enrollmentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubmitEnrollmentRequest"];
                };
            };
            responses: {
                /** @description Enrollment submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            enrollment?: components["schemas"]["Enrollment"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            details?: {
                path?: string;
                message?: string;
            }[];
        };
        /** @enum {string} */
        Role: "FULL_ADMIN" | "COMPANY_ADMIN" | "EMPLOYEE";
        /** @enum {string} */
        InviteTargetRole: "COMPANY_ADMIN" | "EMPLOYEE";
        /** @enum {string} */
        BenefitClass: "FULL_TIME_ELIGIBLE" | "INELIGIBLE";
        /** @enum {string} */
        EmploymentStatus: "ACTIVE" | "TERMED";
        /** @enum {string} */
        PlanType: "MEDICAL" | "DENTAL" | "VISION";
        /** @enum {string} */
        CoverageTier: "EMPLOYEE_ONLY" | "EMPLOYEE_SPOUSE" | "EMPLOYEE_CHILDREN" | "FAMILY";
        /** @enum {string} */
        DependentRelationship: "SPOUSE" | "CHILD";
        /** @enum {string} */
        EnrollmentStatus: "DRAFT" | "SUBMITTED";
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            tenantId: string | null;
            /** Format: uuid */
            sessionId?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["AuthUser"];
        };
        SignupInviteRequest: {
            inviteCode: string;
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirmRequest: {
            token: string;
            newPassword: string;
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            companyId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InviteCode: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            code: string;
            targetRole: components["schemas"]["InviteTargetRole"];
            /** Format: uuid */
            createdByUserId: string;
            /** Format: date-time */
            expiresAt?: string | null;
            maxUses?: number | null;
            usesCount: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string | null;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SecurityEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId?: string | null;
            /** Format: uuid */
            tenantId?: string | null;
            eventType: string;
            /** @enum {string} */
            severity: "INFO" | "WARN" | "ERROR";
            ipAddress?: string | null;
            userAgent?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
        };
        PageInfo: {
            limit: number;
            offset: number;
            returned: number;
            hasMore: boolean;
            nextOffset: number | null;
        };
        EmployeeProfileInput: {
            /**
             * Format: uuid
             * @description Required only for FULL_ADMIN calls to employee-scoped routes.
             */
            employeeUserId?: string;
            employeeId: string;
            firstName: string;
            lastName: string;
            /** Format: date */
            dob: string;
            /** Format: date */
            hireDate: string;
            salaryAmount: number;
            benefitClass: components["schemas"]["BenefitClass"];
            employmentStatus: components["schemas"]["EmploymentStatus"];
        };
        EmployeeProfile: components["schemas"]["EmployeeProfileInput"] & {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PlanYear: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            name: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: uuid */
            createdByUserId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Plan: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            planYearId: string;
            type: components["schemas"]["PlanType"];
            carrier: string;
            planName: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PlanPremiumInput: {
            coverageTier: components["schemas"]["CoverageTier"];
            employeeMonthlyCost: number;
            employerMonthlyCost: number;
        };
        PlanPremium: components["schemas"]["PlanPremiumInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            planId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Dependent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            employeeUserId: string;
            relationship: components["schemas"]["DependentRelationship"];
            firstName: string;
            lastName: string;
            /** Format: date */
            dob: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EnrollmentElection: {
            planType: components["schemas"]["PlanType"];
            /** Format: uuid */
            planId: string;
            coverageTier: components["schemas"]["CoverageTier"];
            employeeMonthlyCost: number;
            employerMonthlyCost: number;
        };
        Enrollment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            employeeUserId: string;
            /** Format: uuid */
            planYearId: string;
            status: components["schemas"]["EnrollmentStatus"];
            /** Format: date */
            effectiveDate: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            confirmationCode: string | null;
            elections: components["schemas"]["EnrollmentElection"][];
            dependentIds: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTenantRequest: {
            name: string;
            companyId?: string;
        };
        CreateInviteCodeRequest: {
            /** Format: date-time */
            expiresAt?: string;
            maxUses?: number;
        };
        CreatePlanYearRequest: {
            name: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
        };
        CreatePlanRequest: {
            /** Format: uuid */
            planYearId: string;
            type: components["schemas"]["PlanType"];
            carrier: string;
            planName: string;
        };
        SetPlanPremiumsRequest: {
            tiers: components["schemas"]["PlanPremiumInput"][];
        };
        CreateDependentRequest: {
            /**
             * Format: uuid
             * @description Required only for FULL_ADMIN calls.
             */
            employeeUserId?: string;
            relationship: components["schemas"]["DependentRelationship"];
            firstName: string;
            lastName: string;
            /** Format: date */
            dob: string;
        };
        EnrollmentElectionInput: {
            planType: components["schemas"]["PlanType"];
            /** Format: uuid */
            planId: string;
            coverageTier: components["schemas"]["CoverageTier"];
        };
        CreateEnrollmentDraftRequest: {
            /** Format: uuid */
            employeeUserId?: string;
            /** Format: uuid */
            planYearId: string;
            elections: components["schemas"]["EnrollmentElectionInput"][];
            dependentIds?: string[];
        };
        SubmitEnrollmentRequest: {
            /** Format: uuid */
            employeeUserId?: string;
        };
        MessageResponse: {
            message: string;
            resetToken?: string;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
